//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<short> year_of_birth { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual positions positions { get; set; }
    }
}
